-- Schema for the Citi Bike workshop.
--
-- Two tables, and the split between them is the whole point:
--
--   ny_citibike.stations        geometry. ~2,500 rows, changes rarely. Stays in Postgres.
--   ny_citibike.station_status  one row per station per poll. Grows forever. Only counted.
--
-- They join on station_key, a bigint. No geometry ever has to reach the side
-- that does the counting, which is why the counting can move to ClickHouse.

CREATE EXTENSION IF NOT EXISTS postgis;

CREATE SCHEMA IF NOT EXISTS ny_citibike;

-- --------------------------------------------------------------------------
-- Dimension
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ny_citibike.stations (
    -- Surrogate integer key. GBFS station_id is a *string*
    -- ("2124037125711300644", and some systems use non-numeric ids), and the
    -- join key is the one thing that crosses to the aggregating side on every
    -- row. A bigint keeps that crossing cheap and gives ClickHouse something
    -- sensible to order on.
    station_key   bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    station_id    text        NOT NULL UNIQUE,   -- as published by GBFS
    name          text,
    short_name    text,
    lat           double precision,
    lon           double precision,
    capacity      integer,
    region_id     text,

    -- Built from lat/lon on load. This column is the reason the geometry side
    -- cannot move: ClickHouse has no equivalent type.
    geom          geometry(Point, 4326)

    -- Deliberately no first_seen/last_seen.
    --
    -- They were here, nothing ever read them, and last_seen actively cost
    -- something: keeping it current meant the sync rewrote all 2,509 rows every
    -- minute, 3.6M no-op writes a day of WAL and replication, on the table this
    -- workshop introduces as the half that barely changes. Feed freshness is
    -- station_status.polled_at, once, for the whole feed.
);

CREATE INDEX IF NOT EXISTS stations_geom_gix ON ny_citibike.stations USING GIST (geom);

-- --------------------------------------------------------------------------
-- Fact
-- --------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS ny_citibike.station_status (
    -- Logical replication needs a replica identity. Without a primary key,
    -- ClickPipes refuses the table outright: "cannot be replicated because
    -- they don't have a valid replica identity". REPLICA IDENTITY FULL would
    -- also clear that, but a bigint key is what the ClickHouse side wants to
    -- order and deduplicate on anyway.
    status_id     bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    station_key   bigint      NOT NULL,

    -- When we fetched the file. UTC, always. GBFS timestamps are epoch
    -- seconds, so there is no local-time ambiguity to inherit here — but
    -- ClickHouse attaches a timezone to DateTime, so the column has to be
    -- unambiguous before it replicates.
    polled_at     timestamptz NOT NULL,

    -- When the station last talked to the operator. Lags polled_at, sometimes
    -- by hours for a station that has dropped off the network.
    last_reported timestamptz,

    num_bikes_available  integer,
    num_ebikes_available integer,
    num_docks_available  integer,
    num_bikes_disabled   integer,
    num_docks_disabled   integer,

    is_installed  boolean,
    is_renting    boolean,
    is_returning  boolean
);

-- The two access patterns the workshop actually uses: "this station over time"
-- (the snapshot diff) and "everything in this window" (the aggregates).
CREATE INDEX IF NOT EXISTS status_station_time_ix
    ON ny_citibike.station_status (station_key, polled_at);
CREATE INDEX IF NOT EXISTS status_time_ix
    ON ny_citibike.station_status (polled_at);

-- Deliberately NO foreign key from station_status to stations.
--
-- A station can appear in station_status.json before it appears in
-- station_information.json, and stations get retired between the two files. A
-- constraint here would reject real observations. The sync procedure in
-- sql/03-postgres-sync.sql loads the dimension before the facts so that a
-- station seen this minute has a station_key, but the guarantee is best-effort
-- by design.

-- --------------------------------------------------------------------------
-- Publication for ClickPipes
-- --------------------------------------------------------------------------
--
-- Named tables, not FOR ALL TABLES. A FOR ALL TABLES publication sweeps up
-- every scratch table anyone creates while poking at the workshop, and each
-- one then has to be dealt with downstream.

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'ny_citibike_pub') THEN
        CREATE PUBLICATION ny_citibike_pub
            FOR TABLE ny_citibike.stations, ny_citibike.station_status;
    END IF;
END
$$;
